import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Providers from "@/app/Providers";

export const metadata = {
  title: "Retail Company Store",
  description: "Generated by Mauricio Donado",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />

          <div className="min-h-screen">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
